name: Frontend CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-sonar-docker:
    runs-on: self-hosted

    steps:
      - name:  Cloner le code
        uses: actions/checkout@v4

      - name:  Vérifier Node.js installé
        run: |
          echo "Node version:"
          node -v
          echo "NPM version:"
          npm -v

      - name: Installer les dépendances
        run: npm install

      - name:  Build Angular App
        run: npm run build -- --configuration=production

      - name:  Installer SonarScanner localement
        run: npm install sonar-scanner --save-dev

      - name:  Analyse SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonar-scanner \
            -Dsonar.projectKey=frontend-angular \
            -Dsonar.sources=src \
            -Dsonar.exclusions=**/*.spec.ts,**/node_modules/** \
            -Dsonar.host.url=http://sonarqube.192.168.224.163.nip.io:9000 \
            -Dsonar.login=$SONAR_TOKEN

      - name:  Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name:  Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name:  Build & Push image Docker
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/mon-frontend:${{ github.sha }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/mon-frontend:latest \
            --push .
